#!/bin/bash


#Check if python 3 is installed. 
echo "Setting up python environment for seqcheck.py"

py_version=$( python3 -V )

cleanVersion=$( echo $py_version | cut -d ' ' -f 2 )
parsedVersion=$(echo "${cleanVersion//./}")
if [[ "$parsedVersion" -lt "370" ]]
then 
    echo "Install Python 3.7 (or newer) before continuing. https://www.python.org/downloads/mac-osx/"
	exit
fi

#if [[ $py_version != *"Python 3.7"* ]]
#then
#	echo "Install Python 3.7 (or newer) before continuing. https://www.python.org/downloads/mac-osx/"
#	exit
#fi

#Makes the HOME/bin directory if it doesnt exist
[ ! -d "$HOME/bin" ] && mkdir ${HOME}/bin
installPath=$HOME/bin/"seqcheck"

echo "Nice, Python3 is installed. Installing seqcheck at: $installPath"

mkdir $installPath

#Copy over all the files to the HOME/bin/seqcheck directory
echo "Copying files now..."
cp config.json $installPath/
cp requirements.txt $installPath/
cp README.md $installPath/
cp seqcheck $installPath/
cp run_seqcheck.py $installPath/
cp construct_lib.csv $installPath/
echo "\"construct_lib\":\"$installPath/construct_lib.csv\" }" >> $installPath/config.json

#Make a virtual env and install dependecies. 
echo "Now, attempting to set up the virual environment..."
pip3 install virtualenv

echo "Still working..."
virtualenv $installPath/seqcheck_env
source $installPath/seqcheck_env/bin/activate
pip3 install -r $installPath/requirements.txt

echo "--------------------------------------"
echo " "
echo "Looks like the environments all set up."
deactivate 

#Add to PATH so the executable can be called from anywhere.
echo "Setting up command line tool..."
chmod +x $installPath/seqcheck
sudo cp seqcheck /usr/local/bin/
sudo chmod 755 /usr/local/bin/seqcheck

echo "--------------------------------------"

